"""E2E template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier): LoRA fine-tuning.

Only the task-specific prose and stage cells live here. Runtime install (pins from
tools/finetune-pins.txt), the embedded pipeline module, and the model pin/stage/verify cells are
produced by the generator from repository sources so they cannot drift from the package.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "whisper_asr_pipeline",
    "repo_name": "whisper-asr-pipeline",
    "stem": "whisper_asr_finetune",
    "notebook_name": "whisper_asr_finetune_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "pipeline_class": "WhisperASRPipeline",
    "weights_key": "whisper-large-v3-turbo",
    # pipeline.py is shared byte for byte with the workshop notebook; the review-fix helpers live in their own module.
    "modules": ["pipeline.py", "tutorial_support.py"],
    "pins_file": "tools/finetune-pins.txt",
    # NOTEBOOK_SPEC 2.2 §5 (WSF-M1): the pins are installed into an isolated uv environment and every later cell runs in
    # a persistent worker there, so a hosted runtime's preloaded packages never force a restart. The lock is compiled with
    # `uv pip compile tools/finetune-pins.txt --python-version 3.12 --python-platform x86_64-manylinux_2_28
    # --generate-hashes --only-binary :all: -o tutorials/requirements-finetune.lock.txt`.
    "isolated_runtime": True,
    "infrastructure_labels": True,
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-finetune.lock.txt",
    "runtime_imports": ["torch", "transformers", "peft"],
    "title": "Whisper large-v3-turbo — DIMER LoRA fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/whisper-asr-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/whisper-asr-pipeline/blob/main/tutorials/whisper_asr_finetune_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-openai%2Fwhisper--large--v3--turbo-ffcc4d?style=flat",
            "https://huggingface.co/openai/whisper-large-v3-turbo",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-openai%2Fwhisper-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/openai/whisper",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2212.04356-b31b1b.svg", "https://arxiv.org/abs/2212.04356"),
    ],
    "capability": "parameter-efficient (LoRA) domain adaptation of the pinned `openai/whisper-large-v3-turbo` weights for automatic speech recognition, evaluated by corpus word error rate before and after adaptation and after a fresh reload of the exported adapter bundle",
    "run_all": (
        "This notebook needs a 16 GiB-class CUDA GPU (Colab: Runtime > Change runtime type > T4 GPU; Kaggle P100/T4 also works) — the earlier version of this notebook took 1002 s end to end on a Kaggle **T4** (14 September 2026, after one manual restart, which this version no longer needs) and 1617.7 s with 4.48 GiB peak GPU memory on a Kaggle P100 (11 September 2026); this version has not been timed yet (RUN11/RUN12; on CPU it runs but takes hours, so reduce `TRAIN_CLIPS`, `EVAL_CLIPS` and `EPOCHS` first). Once that runtime is selected, **Run all** builds an isolated Python environment from the hash-locked pins (the kernel's own packages are left alone, so no restart is needed; a second Run all reuses it), stages and digest-verifies the pinned snapshot, downloads one locale of the public `PolyAI/minds14` corpus at a pinned dataset revision and decodes/resamples it with the pinned `soundfile`/`torchaudio`, draws a seeded train/held-out split and validates every clip into an input manifest, records the zero-shot **baseline** corpus WER through the carried pipeline, attaches LoRA adapters to the verified base weights and trains them for two bounded epochs with AdamW under mixed precision, evaluates the adapted model on the held-out split through the same pipeline and writes the evaluation report, exports the manifested adapter bundle, and reloads it against the verified base snapshot with a weight-level merge check and a transcript agreement check. No repository clone, DIMER worker or service, credential, upload dialog, configuration edit or runtime restart is required (NOTEBOOK_SPEC 2.2 §5)."
    ),
    "byod": (
        "After the sample workflow completes, set `USE_BYOD = True` in Section 4 and choose *Runtime → Run after* from that cell. Supply a `.csv` with `file,text` columns plus the audio files it names, either as a folder or `.zip` in `BYOD_PATH` or through the upload dialog; they enter the same decoding, validation, seeded split, baseline, LoRA training, evaluation, export and fresh-reload cells as the public sample (DAT14). For BYOD the split is derived from what you supply (`BYOD_TRAIN_FRACTION`, 80 / 20 by default) and at least `BYOD_MIN_CLIPS` (10) usable clips are needed; `TRAIN_CLIPS` and `EVAL_CLIPS` apply to the public sample only. Clips longer than 30 seconds are dropped before the split and listed as a finding. Uploads stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "intro": (
        "**What is trained and what is not.** LoRA keeps every original weight matrix $W_0$ frozen and learns a "
        "low-rank correction $W = W_0 + \\frac{\\alpha}{r} B A$; $B$ starts at zero, so at step 0 the adapted model "
        "*is* the base model. Adapters go on the query and value projections of every attention block in both the "
        "32-layer encoder and the 4-layer decoder (the standard Whisper recipe); with rank 32 that is under 1% of "
        "the 809M parameters. What the upstream checkpoint supplies is the weights, tokenizer and feature-extractor "
        "configuration; what the carried pipeline module adds is snapshot verification, the input contract, the "
        "`corpus_word_error_rate`, `validate_inputs`, `export_adapter_bundle`, `verify_adapter_merge` and "
        "`adaptation_report` helpers, and the single decoding path (`WhisperASRPipeline`) that the baseline, the "
        "in-memory adapted model and the reloaded bundle all go through, so their transcripts are comparable. "
        "**Training loss and validation loss are optimisation evidence only** (FT7); the metric that matters is the "
        "corpus WER on the held-out split, and it is tutorial evidence for one small split of one locale, not a "
        "benchmark."
    ),
    "learning_objectives": (
        "install the pinned runtime, read what the carried pipeline module guarantees, resolve and digest-verify the "
        "immutable upstream model revision, load a public labelled speech corpus at a pinned revision (or upload your "
        "own) and validate it into an input manifest, record a zero-shot baseline through the pipeline, attach LoRA "
        "adapters and train them with a plain PyTorch loop whose every knob is explicit, evaluate the adapted model on "
        "the held-out split and read the evaluation report correctly, export a manifested adapter bundle, prove that a "
        "fresh load applies the saved adapter to the base weights, and export machine-readable outputs plus provenance."
    ),
    "exclusions": (
        "full-parameter fine-tuning, encoder-only or decoder-only adaptation, learning-rate schedules, speaker "
        "diarization or identification, character-level metrics for languages without whitespace-delimited words "
        "(`zh-CN`, `ko-KR`), a forgetting check outside the adaptation distribution, or any calibrated "
        "transcript-confidence threshold. Whisper can hallucinate fluent text on silence or music, and the pipeline "
        "does not detect it."
    ),
    "guided_opening": [
        (
            "## How to use this notebook\n\n"
            "**Who this notebook is for.** Learners who can open a hosted notebook (Google Colab or Kaggle), run cells in order and read short "
            "Python and PyTorch, and who want to see how a large pretrained speech model is adapted to a new domain with a low-rank adapter, and "
            "how the result is measured honestly. No prior experience with LoRA or Whisper is assumed: each term is explained where it is first "
            "needed and again in the glossary below. A 16 GiB-class GPU (Colab T4) is required. The **Prerequisites** give the details.\n\n"
            "**Running it.** In Colab choose *Runtime → Change runtime type → T4 GPU*, then *Runtime → Run all*. The default path needs no edit, "
            "no upload, no account, no token and no runtime restart. Section 1 builds the isolated environment (the CUDA build of `torch` is "
            "several GB, so it is one of the slowest steps); training in Section 8 is the longest. A second Run all in the same runtime reuses the "
            "environment.\n\n"
            "**Where the code runs.** The first two code cells run in the notebook kernel: they build the environment and start one Python process "
            "inside it. Every later cell is sent to that process, so the pinned `torch`, `transformers`, `peft`, `numpy` and `datasets` are used "
            "without replacing anything the hosted runtime had already loaded. Printed output and errors come back to the notebook as usual, and "
            "variables persist from cell to cell.\n\n"
            "**Two kinds of cell.** *Infrastructure cells* (Sections 1–3: the isolated install and router, the carried pipeline module and the "
            "pinned-model staging) are collapsed and labelled **Infrastructure**; you may run them without studying their implementation. "
            "*Learner cells* (Sections 4–10) are the machine-learning workflow.\n\n"
            "**Form controls.** Some learner cells start with fields Colab renders as a form: `LOCALE`, `TRAIN_CLIPS`, `EVAL_CLIPS`, `SEED`, "
            "`USE_BYOD`, `BYOD_LANGUAGE`, `BYOD_PATH` and `BYOD_TRAIN_FRACTION` (Section 4); `LORA_RANK` and `LORA_ALPHA` (Section 7); `EPOCHS`, "
            "`BATCH_SIZE`, `GRAD_ACCUM` and `LEARNING_RATE` (Section 8). Leave them at their defaults for the first run. After a change, select "
            "the cell you changed and choose *Runtime → Run after*: every later cell, including the baseline, runs again (Section 6 rebuilds the "
            "baseline pipeline itself).\n\n"
            "**Section tags.** Each learner heading carries one tag. **[Concept]** — what the model does and why. **[Evaluation practice]** — how "
            "the evidence is produced and how to read it. **[Engineering]** — reproducibility, provenance and packaging.\n\n"
            "**Predict, then check.** Before each principal result a **Predict before running** prompt asks you to commit to an expectation; after "
            "it, **What to notice** describes normal output and a collapsed **Check your reasoning** block gives a worked answer. Write your own "
            "answer first, then open it. The numbers the answers quote come from the recorded P100 run of an earlier version of this notebook "
            "with the same defaults (11 September 2026); no run of this revision is recorded yet."
        ),
        (
            "## The task: Input → Model/System → Output\n\n"
            "| Stage | Input | Model / system | Output |\n"
            "|---|---|---|---|\n"
            "| **Load and validate** | one MINDS-14 locale at a pinned revision (or your `.csv` + audio), resampled to 16 kHz | the carried `validate_inputs` plus two training rules | a seeded train / held-out split and an input manifest |\n"
            "| **Baseline** | the held-out clips | Whisper large-v3-turbo, zero-shot, through `WhisperASRPipeline` | baseline corpus WER and its edit breakdown |\n"
            "| **Adapt** | the training clips and their transcripts | LoRA (rank 32) on the q/v projections, AdamW, mixed precision | a trained adapter (under 1 % of the parameters) |\n"
            "| **Evaluate and reload** | the same held-out clips | the adapted model, then the exported bundle reloaded on the verified base | adapted and reloaded WER, a merge check, an adapter bundle |\n\n"
            "## Roadmap\n\n"
            "| Section | Tag | What happens | What you read |\n"
            "|---|---|---|---|\n"
            "| 1. Install the pinned runtime | [Engineering] | isolated environment built; later cells routed to it | versions, CUDA |\n"
            "| 2. Pipeline code | [Engineering] | the repository's module, carried verbatim | nothing to run by hand |\n"
            "| 3. Pin, stage and verify the model | [Engineering] | snapshot downloaded and digest-checked | the verified files |\n"
            "| 4. Load the data | [Evaluation practice] | corpus (or BYOD), resampling, seeded split | counts, dropped clips, duplicates |\n"
            "| 5. Validate | [Evaluation practice] | every clip checked; findings recorded | the manifest summary |\n"
            "| 6. Baseline | [Evaluation practice] | zero-shot WER on the held-out clips | WER and edit breakdown |\n"
            "| 7. Attach LoRA | [Concept] | adapters on the verified base weights | trainable share |\n"
            "| 8. Train | [Concept] | a plain PyTorch loop | losses per epoch |\n"
            "| 9. Evaluate | [Evaluation practice] | adapted WER beside the baseline | the gain and what it is made of |\n"
            "| 10. Export and reload | [Engineering] | adapter bundle, fresh reload, merge check | reloaded WER, agreement |\n"
            "| 11. Activity (optional) | [Concept] | change `EPOCHS` and compare | your comparison |\n"
            "| Troubleshooting, Conclusion | — | recovery, your notes | when needed |\n\n"
            "**Fast path.** Short on time? Run all, then read Sections 6, 8 and 9 and the conclusion."
        ),
        (
            "<details>\n<summary><strong>Glossary</strong> — open when a term is unfamiliar</summary>\n\n"
            "| Term | Meaning in this notebook |\n"
            "|---|---|\n"
            "| **LoRA** | Low-Rank Adaptation: the original weights stay frozen and a small correction `B @ A` is learned for chosen layers. |\n"
            "| **Rank `r` / alpha** | The inner size of `B @ A` (here 32) and its scale (`alpha / r`); larger rank means more trainable parameters. |\n"
            "| **q / v projections** | The query and value matrices of each attention block, where the adapters are attached. |\n"
            "| **Log-Mel spectrogram** | The 128-band time-frequency picture of 30 seconds of audio that Whisper's encoder reads. |\n"
            "| **Teacher forcing** | During training the decoder is fed the correct previous tokens and scored on predicting the next one. |\n"
            "| **`-100` label** | A padding position the loss ignores. |\n"
            "| **Mixed precision / gradient scaler** | Matrix products run in float16 for speed; the scaler keeps small gradients from rounding to zero. |\n"
            "| **Training / validation loss** | Teacher-forced cross-entropy on the training and held-out clips: optimisation evidence, not the result. |\n"
            "| **Corpus WER** | Total word edits (substitutions + insertions + deletions) over total reference words, after case and punctuation normalisation. |\n"
            "| **Edit breakdown** | The same errors split by type; shows whether adaptation changed spelling (substitutions) or what was heard. |\n"
            "| **Zero-shot baseline** | The unmodified model on the same held-out clips: the number every adapted figure is read against. |\n"
            "| **Adapter bundle** | The exported adapter weights, configuration, metrics, provenance and a digest manifest. |\n"
            "| **Merge check** | Proof that a fresh load really applied the saved adapter: `W_reloaded = W_base + (alpha / r) B @ A` on one probe layer. |\n"
            "| **Forgetting** | Adaptation can make the model worse outside the training domain; this notebook does not measure it. |\n"
            "| **Isolated environment** | A separate Python built from hash-locked pins, in which every learner cell runs. |\n\n"
            "</details>"
        ),
    ],
    "prerequisites": [
        "- **Runtime:** a fresh **Linux x86_64** runtime with a 16 GiB-class CUDA GPU (Google Colab **T4** or Kaggle P100/T4). The kernel's own Python version does not matter: Section 1 builds a separate environment with CPython 3.12.12 from the hash-locked pins and every later cell runs there. Timing of earlier versions of this notebook with the default configuration: 1002 s end to end on a Kaggle T4 (14 September 2026, the standalone version before this one; it needed one manual restart after the install cell); 1617.7 s on a Kaggle P100 (11 September 2026: 236 s install, 109 s baseline, 1106.7 s training for 100 optimizer steps, 72 s adapted evaluation, 75 s export and reload; 4.48 GiB peak GPU memory). This version has not been timed yet; the isolated-environment build replaces the in-kernel install. CPU execution is supported only as a reduced smoke test: lower `TRAIN_CLIPS`, `EVAL_CLIPS` and `EPOCHS` first, or the training cell will take hours.",
        "- **Knowledge:** basic Python and PyTorch; what a waveform, a sampling rate, a log-mel spectrogram, teacher forcing and a word error rate are; the idea of a low-rank adapter.",
        "- **Data:** the default sample is one locale of the public `PolyAI/minds14` banking-intent corpus (CC-BY-4.0), fetched from the Hugging Face Hub at the pinned dataset revision `40ce77cb32a384e4d50a568e1ec39ac804019d33` and decoded with the pinned `soundfile`/`torchaudio` — no private data is needed. Optional BYOD upload is gated off by default so the sample path can run top-to-bottom without interaction. Expected BYOD input: one `.csv` with `file,text` columns plus the audio files it names (WAV/FLAC/OGG readable by `soundfile`, any rate, mono or stereo, each at most 30 seconds; longer clips are dropped and listed), as a folder or `.zip` in `BYOD_PATH` or all selected in one upload dialog; at least 10 usable clips, split 80 / 20 by default (`BYOD_TRAIN_FRACTION`); set `BYOD_LANGUAGE` to the ISO code Whisper should decode in. A few dozen clips are enough to run the pipeline end to end, not to measure a reliable gain. Do not upload confidential or restricted data to a hosted notebook environment unless you are authorized to do so. Uploaded inputs remain in the notebook runtime; this pipeline does not send them to a third-party inference API. An adapter trained on the default sample inherits CC-BY-4.0 attribution obligations.",
    ],
    "cells": [
        {
            "md": (
                "## 4. Load a public labelled speech set or optional BYOD · [Evaluation practice]\n\n"
                "The default path loads one locale of the public `PolyAI/minds14` banking-intent corpus (CC-BY-4.0) at the "
                "pinned dataset revision `40ce77cb32a384e4d50a568e1ec39ac804019d33` so the bytes cannot drift: short "
                "telephone-quality utterances stored at **8 kHz**, each with a cased, punctuated transcription. Whisper "
                "expects 16 kHz input, so every clip is decoded with the pinned `soundfile` and resampled with the pinned "
                "`torchaudio` — the same resampler the transformers ASR pipeline applies at inference time, so training and "
                "inference see identical audio. A seeded shuffle then takes `TRAIN_CLIPS` clips for adaptation and a disjoint "
                "`EVAL_CLIPS` for the held-out baseline/adapted comparison (SPL1; random splitting assumes the utterances are "
                "independent, SPL3); the split is recorded as a digest in the exported provenance.\n\n"
                "The locale list is restricted to languages whose transcripts are whitespace-delimited: the package's word "
                "error rate splits on whitespace, so it is not a meaningful metric for the corpus's `zh-CN` and `ko-KR` "
                "locales. BYOD is optional and disabled by default; expected input is a `transcripts.csv` with `file,text` "
                "columns plus the referenced audio files, all selected in the same upload dialog, and `BYOD_LANGUAGE` names "
                "the decoding language. BYOD files come from `BYOD_PATH` (a folder or a `.zip`; works in any Jupyter runtime) "
                "or, when it is empty, from the upload dialog; a missing `.csv`, a missing `file,text` header and every audio file the "
                "`.csv` names but you did not supply are refused by name. For BYOD the split is derived from what you supplied: "
                "`BYOD_TRAIN_FRACTION` (0.8) of the usable clips train and the rest are held out, and at least `BYOD_MIN_CLIPS` (10) "
                "usable clips are required; `TRAIN_CLIPS` and `EVAL_CLIPS` apply to the public sample only.\n\n"
                "**Clips longer than 30 seconds.** Whisper's window is 30 seconds, so a longer clip would have its supervision cut. "
                "Such clips are **dropped before the split**, counted in the printed dictionary and listed by id as a finding in the "
                "Section 5 input manifest — nothing is dropped silently. Look for a dictionary naming the corpus, the language, the "
                "clip counts (including any dropped), the split digest, the clip-length statistics and how many held-out transcripts "
                "also occur, word for word, in the training split."
            ),
            "code": (
                "import csv\n"
                "import hashlib\n"
                "import io\n"
                "import random\n"
                "import zipfile\n"
                "from pathlib import Path\n\n"
                "import soundfile as sf\n"
                "import torchaudio\n"
                "from datasets import Audio, load_dataset\n\n"
                "LOCALE = 'en-US'  # @param ['en-US', 'en-GB', 'en-AU', 'de-DE', 'fr-FR', 'es-ES', 'it-IT', 'nl-NL', 'pl-PL', 'pt-PT', 'ru-RU', 'cs-CZ']\n"
                "TRAIN_CLIPS = 400  # @param {{type:\"integer\"}}\n"
                "EVAL_CLIPS = 100  # @param {{type:\"integer\"}}\n"
                "SEED = 0  # @param {{type:\"integer\"}}\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_LANGUAGE = 'en'  # @param {{type:\"string\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "BYOD_TRAIN_FRACTION = 0.8  # @param {{type:\"number\"}}\n"
                "BYOD_MIN_CLIPS = 10\n"
                "SAMPLE_DATASET = 'PolyAI/minds14'\n"
                "SAMPLE_DATASET_REVISION = '40ce77cb32a384e4d50a568e1ec39ac804019d33'\n"
                "TARGET_RATE = 16_000\n\n\n"
                "def decode_clip(name, raw_bytes):\n"
                "    # Decode with the pinned soundfile (decode_audio names the file it refuses), then resample with the pinned\n"
                "    # torchaudio: the datasets audio feature would decode through torchcodec/FFmpeg, which this runtime does not pin.\n"
                "    waveform, rate = decode_audio(name, raw_bytes)\n"
                "    if rate != TARGET_RATE:\n"
                "        waveform = torchaudio.functional.resample(torch.from_numpy(waveform), rate, TARGET_RATE).numpy()\n"
                "    return waveform\n\n\n"
                "def read_byod_files(path):\n"
                "    source = Path(path)\n"
                "    if source.is_dir():\n"
                "        return {{p.name: p.read_bytes() for p in sorted(source.iterdir()) if p.is_file() and not p.name.startswith('.')}}\n"
                "    if source.suffix.lower() == '.zip':\n"
                "        with zipfile.ZipFile(source) as archive:\n"
                "            return {{Path(n).name: archive.read(n) for n in archive.namelist() if not n.endswith('/') and '__MACOSX/' not in n and not Path(n).name.startswith('.')}}\n"
                "    raise ValueError(f'BYOD_PATH must be a folder or a .zip holding the .csv and the audio files: {{path}}')\n\n\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH:\n"
                "        uploaded = read_byod_files(BYOD_PATH)\n"
                "    else:\n"
                "        from google.colab import files\n"
                "        uploaded = files.upload()\n"
                "    csv_names = [name for name in uploaded if name.lower().endswith('.csv')]\n"
                "    if len(csv_names) != 1:\n"
                "        raise ValueError(f'BYOD needs exactly one .csv with file,text columns; found {{csv_names or \"none\"}} among {{len(uploaded)}} file(s)')\n"
                "    manifest_name = csv_names[0]\n"
                "    rows = list(csv.DictReader(io.StringIO(uploaded[manifest_name].decode('utf-8-sig'))))\n"
                "    if not rows or not {{'file', 'text'}} <= set(rows[0]):\n"
                "        raise ValueError(f'{{manifest_name}}: needs a header with file,text columns and at least one row')\n"
                "    missing = [row['file'] for row in rows if row['file'] not in uploaded]\n"
                "    if missing:\n"
                "        raise ValueError(f'{{manifest_name}} names {{len(missing)}} audio file(s) that were not supplied: {{missing[:5]}}')\n"
                "    clips = [{{'id': row['file'], 'audio': decode_clip(row['file'], uploaded[row['file']]), 'text': row['text'].strip()}} for row in rows]\n"
                "    LANGUAGE = BYOD_LANGUAGE.strip().lower()\n"
                "    DATASET = {{'name': 'BYOD', 'config': manifest_name, 'revision': None, 'license': None}}\n"
                "    sample_kind = 'BYOD'\n"
                "else:\n"
                "    ds = load_dataset(SAMPLE_DATASET, LOCALE, split='train', revision=SAMPLE_DATASET_REVISION)\n"
                "    ds = ds.cast_column('audio', Audio(decode=False))\n"
                "    clips = [{{'id': row['path'], 'audio': decode_clip(row['path'], row['audio']['bytes']), 'text': row['transcription'].strip()}} for row in ds]\n"
                "    LANGUAGE = LOCALE.split('-')[0]\n"
                "    DATASET = {{'name': SAMPLE_DATASET, 'config': LOCALE, 'revision': SAMPLE_DATASET_REVISION, 'license': 'CC-BY-4.0'}}\n"
                "    sample_kind = 'public-sample'\n\n"
                "# WSF-m1: clips over the 30 s window are dropped before the split, and listed (Section 5 records them as a finding).\n"
                "DROPPED_OVER_30S = [c['id'] for c in clips if len(c['audio']) / TARGET_RATE > MAX_CHUNK_LENGTH_S]\n"
                "clips = [c for c in clips if len(c['audio']) / TARGET_RATE <= MAX_CHUNK_LENGTH_S]\n"
                "if USE_BYOD:\n"
                "    if len(clips) < BYOD_MIN_CLIPS:\n"
                "        raise ValueError(f'BYOD needs at least {{BYOD_MIN_CLIPS}} usable clips of at most {{MAX_CHUNK_LENGTH_S}} s; {{len(clips)}} remain ({{len(DROPPED_OVER_30S)}} dropped as too long)')\n"
                "    TRAIN_CLIPS = min(len(clips) - 1, max(1, round(BYOD_TRAIN_FRACTION * len(clips))))\n"
                "    EVAL_CLIPS = len(clips) - TRAIN_CLIPS\n"
                "if TRAIN_CLIPS < 1 or EVAL_CLIPS < 1 or TRAIN_CLIPS + EVAL_CLIPS > len(clips):\n"
                "    raise ValueError(f'TRAIN_CLIPS + EVAL_CLIPS ({{TRAIN_CLIPS}} + {{EVAL_CLIPS}}) must fit in the {{len(clips)}} available clips; lower TRAIN_CLIPS or EVAL_CLIPS in this cell')\n"
                "order = list(range(len(clips)))\n"
                "random.Random(SEED).shuffle(order)\n"
                "train_clips = [clips[i] for i in order[:TRAIN_CLIPS]]\n"
                "eval_clips = [clips[i] for i in order[TRAIN_CLIPS:TRAIN_CLIPS + EVAL_CLIPS]]\n"
                "SPLIT_DIGEST = hashlib.sha256('\\n'.join(c['id'] + '\\t' + c['text'] for c in train_clips + eval_clips).encode('utf-8')).hexdigest()\n"
                "seconds = [len(c['audio']) / TARGET_RATE for c in train_clips + eval_clips]\n"
                "# WSF-m3: a held-out transcript that also occurs in training (after normalisation) is easier than a new phrasing.\n"
                "train_texts = {{normalise_transcript(c['text']) for c in train_clips}}\n"
                "EVAL_TRANSCRIPTS_IN_TRAIN = sum(normalise_transcript(c['text']) in train_texts for c in eval_clips)\n"
                "print({{'dataset': DATASET, 'language': LANGUAGE, 'train_clips': len(train_clips), 'eval_clips': len(eval_clips), 'dropped_over_30s': len(DROPPED_OVER_30S), 'split_digest': SPLIT_DIGEST[:16], 'seconds_mean': round(sum(seconds) / len(seconds), 2), 'seconds_max': round(max(seconds), 2), 'eval_transcripts_also_in_train': EVAL_TRANSCRIPTS_IN_TRAIN}})\n"
                "print({{'example_text': train_clips[0]['text']}})"
            ),
        },
        {
            "md": (
                "## 5. Validate every clip → input manifest · [Evaluation practice]\n\n"
                "`validate_inputs` is the pipeline's public validation stage and is applied to **every** train and held-out "
                "clip before any model runs (VAL1): each waveform must satisfy the same contract `transcribe` enforces "
                "(`TASKS`, the `MIN_CHUNK_LENGTH_S`–`MAX_CHUNK_LENGTH_S` window), and this notebook adds the two rules the "
                "training loop needs — a non-empty transcript, and a clip no longer than `MAX_CHUNK_LENGTH_S` seconds, "
                "because Whisper's fixed 30-second window would truncate a longer clip's supervision (VAL6/VAL7: nothing is "
                "truncated; longer clips were dropped before the split in Section 4 and are recorded here as a `clips-over-30s` "
                "finding with their ids, and a clip that still breaks either rule stops the run). The per-clip manifests "
                "are folded into one input manifest written to `outputs/{stem}_input_manifest.json`. To show what rejection "
                "looks like, the cell also validates a request that breaks the chunk ceiling and records the pipeline's own "
                "error message as a finding."
            ),
            "code": (
                "import json\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "print({{'ceilings': {{'TASKS': list(TASKS), 'MIN_CHUNK_LENGTH_S': MIN_CHUNK_LENGTH_S, 'MAX_CHUNK_LENGTH_S': MAX_CHUNK_LENGTH_S, 'TARGET_RATE': TARGET_RATE}}}})\n"
                "input_manifest = {{'schema': dict(INPUT_SCHEMA), 'inputs': [], 'task': 'transcribe', 'language': LANGUAGE, 'chunk_length_s': MAX_CHUNK_LENGTH_S, 'split': {{'train': len(train_clips), 'eval': len(eval_clips), 'seed': SEED, 'digest': SPLIT_DIGEST}}, 'verdict': 'accepted', 'findings': [], 'model_id': MODEL_ID, 'model_revision': MODEL_REVISION}}\n"
                "for role, clip_list in (('train', train_clips), ('eval', eval_clips)):\n"
                "    for clip in clip_list:\n"
                "        audio_input = {{'array': clip['audio'], 'sampling_rate': TARGET_RATE}}\n"
                "        entry = validate_inputs(audio_input, language=LANGUAGE, task='transcribe', names=[clip['id']])['inputs'][0]\n"
                "        if not clip['text']:\n"
                "            raise ValueError(f\"{{clip['id']}}: empty transcript; every training and evaluation clip needs a reference\")\n"
                "        if entry['seconds'] > MAX_CHUNK_LENGTH_S:\n"
                "            raise ValueError(f\"{{clip['id']}}: {{entry['seconds']}} s exceeds the {{MAX_CHUNK_LENGTH_S}} s training window; trim it rather than letting the window truncate its supervision\")\n"
                "        input_manifest['inputs'].append({{**entry, 'role': role, 'reference_words': len(clip['text'].split())}})\n"
                "if DROPPED_OVER_30S:\n"
                "    input_manifest['findings'].append({{'input': 'clips-over-30s', 'verdict': 'dropped before the split', 'count': len(DROPPED_OVER_30S), 'ids': DROPPED_OVER_30S}})\n"
                "# Demonstrate rejection on a request that breaks a ceiling; the finding is recorded, not swallowed.\n"
                "try:\n"
                "    validate_inputs({{'array': eval_clips[0]['audio'], 'sampling_rate': TARGET_RATE}}, chunk_length_s=MAX_CHUNK_LENGTH_S + 1)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'oversized-chunk-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'validated_clips': len(input_manifest['inputs']), 'verdict': input_manifest['verdict'], 'findings': input_manifest['findings']}})"
            ),
        },
        {
            "md": (
                "## 6. Record the zero-shot baseline · [Evaluation practice]\n\n"
                "`pipe` was built in Section 3 from the digest-verified snapshot (float16 on CUDA, float32 on CPU). This cell releases it "
                "at the end, so when you re-run from Section 4 (BYOD, or the activity) it is rebuilt here from the same verified snapshot "
                "with `WhisperASRPipeline.from_pretrained(weights_dir=WEIGHTS_DIR, allow_download=False)` — no download, no need to go back "
                "to Section 3. Before "
                "anything is trained, the unmodified model transcribes the held-out clips through `WhisperASRPipeline.transcribe`, "
                "and `corpus_word_error_rate` (total word edits over total reference words, after the package's case and "
                "punctuation normalisation) is recorded as the **baseline** (EVAL10: the naive comparison every adapted number "
                "is read against). The errors are also split into **substitutions, insertions and deletions** "
                "(`word_error_breakdown`), so you can later see which kind adaptation changes. The pipeline is then released so the "
                "training model has the GPU to itself. Look for the baseline WER, its edit breakdown and three reference/hypothesis "
                "pairs.\n\n"
                "**Predict before running:** MINDS-14 references are written by people in their own style (lower case, little "
                "punctuation, numbers sometimes spelled out), while Whisper writes cased, punctuated text with digits. Will the "
                "zero-shot WER be near 0.05, near 0.2, or above 0.4? Which edit type will dominate?"
            ),
            "code": (
                "import gc\n"
                "import time\n\n\n"
                "def transcribe_all(asr, clip_list):\n"
                "    return [asr.transcribe({{'array': c['audio'], 'sampling_rate': TARGET_RATE}}, language=LANGUAGE, task='transcribe')['text'] for c in clip_list]\n\n\n"
                "eval_references = [c['text'] for c in eval_clips]\n"
                "if 'pipe' not in globals():\n"
                "    # This cell releases `pipe` below; a re-run from Section 4 rebuilds it from the verified snapshot (no download).\n"
                "    pipe = WhisperASRPipeline.from_pretrained(weights_dir=WEIGHTS_DIR, allow_download=False)\n"
                "DEVICE = pipe.device\n"
                "started = time.time()\n"
                "baseline_transcripts = transcribe_all(pipe, eval_clips)\n"
                "baseline_wer = corpus_word_error_rate(eval_references, baseline_transcripts)\n"
                "baseline_edits = word_error_breakdown(eval_references, baseline_transcripts)\n"
                "print({{'device': DEVICE, 'source': pipe.source, 'baseline_wer': round(baseline_wer, 4), 'edits': baseline_edits, 'seconds': round(time.time() - started, 1)}})\n"
                "for reference, hypothesis in list(zip(eval_references, baseline_transcripts))[:3]:\n"
                "    print({{'reference': reference, 'baseline': hypothesis, 'wer': round(word_error_rate(reference, hypothesis), 3)}})\n"
                "del pipe\n"
                "gc.collect()\n"
                "if DEVICE.startswith('cuda'):\n"
                "    torch.cuda.empty_cache()"
            ),
        },
        {
            "md": (
                "**What to notice (Section 6):** the baseline WER, the three edit counts that add up to it, and how the three example "
                "transcripts differ from their references.\n\n"
                "<details><summary>Check your reasoning</summary>Expect a high number: the earlier recorded P100 run of this notebook measured "
                "0.4387 on the same default split. Much of it is not mis-heard speech: the references are noisy, informal transcriptions, so "
                "Whisper's spelling, numbers and contractions count as substitutions even when the words were understood. That is why the "
                "baseline matters: the adapted number is read against it, on the same clips and references, not against zero.</details>\n\n"
                "## 7. Attach LoRA adapters to the verified base weights · [Concept]\n\n"
                "`load_model(weights_dir=WEIGHTS_DIR)` re-reads the **same digest-verified snapshot** Section 3 staged (no "
                "second download, no Hub call) and the model is promoted to float32 master weights (mixed precision runs the "
                "matmuls in float16); gradient checkpointing is enabled so the encoder's 30-second activations fit a 16 GiB "
                "card at batch size 4. The forced decoder prompt is cleared so training and generation both derive the "
                "language/task prefix from the labels and the `generate` arguments rather than a config default. One frozen "
                "weight (`PROBE_MODULE`) is copied before the adapters are attached so Section 10 can prove, independently of "
                "how much the transcripts moved, that a fresh load applies the saved adapter to the base weights. Look for the "
                "trainable-parameter count and its share of the total (FT5)."
            ),
            "code": (
                "from peft import LoraConfig, get_peft_model\n\n"
                "LORA_RANK = 32  # @param {{type:\"integer\"}}\n"
                "LORA_ALPHA = 64  # @param {{type:\"integer\"}}\n"
                "LORA_TARGETS = ['q_proj', 'v_proj']\n\n"
                "base_model, processor = load_model(device=DEVICE, weights_dir=WEIGHTS_DIR, allow_download=False)\n"
                "base_model = base_model.float()\n"
                "PROBE_MODULE = 'model.decoder.layers.0.self_attn.q_proj'\n"
                "probe_base_weight = base_model.get_submodule(PROBE_MODULE).weight.detach().to('cpu', torch.float32).clone()\n"
                "base_model.config.forced_decoder_ids = None\n"
                "base_model.generation_config.forced_decoder_ids = None\n"
                "base_model.config.use_cache = False\n"
                "base_model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={{'use_reentrant': False}})\n\n"
                "lora_config = LoraConfig(r=LORA_RANK, lora_alpha=LORA_ALPHA, lora_dropout=0.05, bias='none', target_modules=LORA_TARGETS)\n"
                "model = get_peft_model(base_model, lora_config)\n"
                "trainable_params, all_params = model.get_nb_trainable_parameters()\n"
                "print({{'lora_targets': LORA_TARGETS, 'trainable_parameters': trainable_params, 'all_parameters': all_params, 'trainable_percent': round(100 * trainable_params / all_params, 3), 'dtype': str(next(model.parameters()).dtype)}})"
            ),
        },
        {
            "md": (
                "## 8. Train · [Concept]\n\n"
                "The loop is deliberately plain PyTorch rather than a `Trainer`, so every moving part is visible (FT4/FT6):\n\n"
                "- **Features and labels.** Each clip becomes a 128-bin log-mel spectrogram padded to Whisper's fixed 30-second window by the pinned processor. The label sequence is the tokenizer's rendering of the transcript with its language/task prefix, minus the leading start token (the model prepends it when it shifts labels right), padded with `-100` so padding is ignored by the loss.\n"
                "- **Mixed precision.** On CUDA the forward pass runs under float16 autocast with a gradient scaler; the LoRA weights and optimizer state stay in float32. On CPU everything is float32 (ENV5).\n"
                "- **AdamW at a constant learning rate** (`1e-3` is the usual LoRA starting point for Whisper) with `GRAD_ACCUM` micro-batches per optimizer step; there is no warmup or decay schedule. `SEED` drives the split and the epoch shuffles; non-deterministic CUDA kernels remain a source of run-to-run variability (ENV7/ENV8).\n"
                "- **Validation loss** is the teacher-forced cross-entropy on the held-out clips after each epoch. It tracks whether the adapter is still learning; WER, the metric that matters, is measured in the next section (FT7). The held-out clips are scored for loss only; no "
                "epoch or setting is chosen by it here, which is why they can also serve as the final test (do not copy this into a loop "
                "that picks the best epoch on them).\n\n"
                "**Predict before running:** over two epochs, will the training loss fall? Will the validation loss fall in both "
                "epochs, or could it rise in the second while WER still improves?"
            ),
            "code": (
                "EPOCHS = 2  # @param {{type:\"integer\"}}\n"
                "BATCH_SIZE = 4  # @param {{type:\"integer\"}}\n"
                "GRAD_ACCUM = 2  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 1e-3  # @param {{type:\"number\"}}\n\n"
                "processor.tokenizer.set_prefix_tokens(language=LANGUAGE, task='transcribe')\n"
                "decoder_start = model.config.decoder_start_token_id\n"
                "use_amp = DEVICE.startswith('cuda')\n\n\n"
                "def make_batch(clip_list):\n"
                "    features = processor.feature_extractor([c['audio'] for c in clip_list], sampling_rate=TARGET_RATE, return_tensors='pt').input_features\n"
                "    label_rows = []\n"
                "    for c in clip_list:\n"
                "        ids = processor.tokenizer(c['text']).input_ids\n"
                "        if ids and ids[0] == decoder_start:\n"
                "            ids = ids[1:]\n"
                "        label_rows.append(ids)\n"
                "    width = max(len(ids) for ids in label_rows)\n"
                "    labels = torch.full((len(label_rows), width), -100, dtype=torch.long)\n"
                "    for row, ids in enumerate(label_rows):\n"
                "        labels[row, :len(ids)] = torch.tensor(ids)\n"
                "    return features.to(DEVICE), labels.to(DEVICE)\n\n\n"
                "def batches(clip_list, size):\n"
                "    for start in range(0, len(clip_list), size):\n"
                "        yield clip_list[start:start + size]\n\n\n"
                "def evaluate_loss(clip_list):\n"
                "    model.eval()\n"
                "    total_loss, total_tokens = 0.0, 0\n"
                "    with torch.inference_mode():\n"
                "        for batch in batches(clip_list, BATCH_SIZE):\n"
                "            features, labels = make_batch(batch)\n"
                "            with torch.autocast(device_type='cuda', dtype=torch.float16, enabled=use_amp):\n"
                "                loss = model(input_features=features, labels=labels).loss\n"
                "            count = int((labels != -100).sum())\n"
                "            total_loss += loss.item() * count\n"
                "            total_tokens += count\n"
                "    return total_loss / total_tokens\n\n\n"
                "optimizer = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=LEARNING_RATE)\n"
                "scaler = torch.amp.GradScaler('cuda', enabled=use_amp)\n"
                "shuffler = random.Random(SEED)\n"
                "if use_amp:\n"
                "    torch.cuda.reset_peak_memory_stats()\n"
                "started = time.time()\n"
                "history = []\n"
                "OPTIMIZER_STEPS = 0\n"
                "for epoch in range(1, EPOCHS + 1):\n"
                "    model.train()\n"
                "    epoch_clips = train_clips[:]\n"
                "    shuffler.shuffle(epoch_clips)\n"
                "    optimizer.zero_grad(set_to_none=True)\n"
                "    epoch_loss, epoch_tokens, pending, epoch_steps = 0.0, 0, 0, 0\n"
                "    micro_batches = list(batches(epoch_clips, BATCH_SIZE))\n"
                "    for step, batch in enumerate(micro_batches, start=1):\n"
                "        features, labels = make_batch(batch)\n"
                "        with torch.autocast(device_type='cuda', dtype=torch.float16, enabled=use_amp):\n"
                "            loss = model(input_features=features, labels=labels).loss\n"
                "        # The window is measured from its own first micro-batch, so the last (possibly short)\n"
                "        # window is scaled by its true size and still takes its optimizer step.\n"
                "        window_start = ((step - 1) // GRAD_ACCUM) * GRAD_ACCUM\n"
                "        window = min(GRAD_ACCUM, len(micro_batches) - window_start)\n"
                "        scaler.scale(loss / window).backward()\n"
                "        count = int((labels != -100).sum())\n"
                "        epoch_loss += loss.item() * count\n"
                "        epoch_tokens += count\n"
                "        pending += 1\n"
                "        if pending == window:\n"
                "            scaler.step(optimizer)\n"
                "            scaler.update()\n"
                "            optimizer.zero_grad(set_to_none=True)\n"
                "            pending = 0\n"
                "            epoch_steps += 1\n"
                "    expected_steps = -(-len(micro_batches) // GRAD_ACCUM)\n"
                "    if epoch_steps != expected_steps or pending:\n"
                "        raise RuntimeError(f'epoch {{epoch}} took {{epoch_steps}} optimizer steps, expected {{expected_steps}} ({{pending}} micro-batches left unstepped)')\n"
                "    OPTIMIZER_STEPS += epoch_steps\n"
                "    train_loss = epoch_loss / epoch_tokens\n"
                "    validation_loss = evaluate_loss(eval_clips)\n"
                "    history.append({{'epoch': epoch, 'train_loss': round(train_loss, 4), 'validation_loss': round(validation_loss, 4), 'optimizer_steps': epoch_steps}})\n"
                "    print(history[-1])\n"
                "TRAINING_SECONDS = round(time.time() - started, 1)\n"
                "PEAK_GPU_GIB = round(torch.cuda.max_memory_allocated() / 1024 ** 3, 2) if use_amp else None\n"
                "print({{'training_seconds': TRAINING_SECONDS, 'peak_gpu_gib': PEAK_GPU_GIB, 'optimizer_steps_total': OPTIMIZER_STEPS}})"
            ),
        },
        {
            "md": (
                "**What to notice (Section 8):** one row per epoch with training loss, validation loss and optimizer steps; the training "
                "time and peak GPU memory.\n\n"
                "<details><summary>Check your reasoning</summary>Training loss falls (0.517 → 0.283 in the earlier recorded run). Validation "
                "loss can rise in epoch 2 (0.578 → 0.612 there) while WER still improves: loss scores the probability of every reference "
                "token under teacher forcing, WER scores the words beam search actually writes, and a model can grow over-confident on "
                "tokens it gets wrong while writing more matching words. A rising validation loss is a warning about overfitting, not a "
                "verdict; the WER in Section 9 is the measurement.</details>\n\n"
                "## 9. Evaluate the adapted model → evaluation report · [Evaluation practice]\n\n"
                "The live LoRA model is wrapped in the same pipeline that produced the baseline (`WhisperASRPipeline.from_model`), "
                "so the adapted transcripts come from exactly the decoding path a user of the package gets (5-beam search, the "
                "model's 448-token limit) — not from a hand-rolled `generate` call with different settings, which can disagree "
                "with the pipeline on near-tie clips (EVAL8). On CUDA the model is first cast to float16, the precision the "
                "pipeline serves at. `adaptation_report` then writes `outputs/{stem}_evaluation_report.json`: baseline and "
                "adapted corpus WER, the zero-shot baseline as the comparison, the loss history as optimisation evidence, and "
                "the verdict `sample-sanity` (EVAL6) — one seeded split of one locale says whether the adapter helped *here*, "
                "not how it generalises. The edit breakdown is printed beside the baseline's, with the count of held-out transcripts "
                "that also occur word for word in the training split (Section 4). A few changed clips are shown side by side.\n\n"
                "**Read the gain carefully.** In the earlier recorded run every held-out transcript moved toward the corpus's lower-case, "
                "unpunctuated reference style. Part of any WER gain here can therefore be the adapter learning MINDS-14's spelling "
                "conventions (`50` versus `fifty`, contractions) rather than hearing better. The normalisation removes case and "
                "punctuation only, so compare the substitution counts and read the changed clips before calling it better recognition.\n\n"
                "**Predict before running:** will the adapted WER be lower than the baseline? If so, which edit type will shrink most?"
            ),
            "code": (
                "model.eval()\n"
                "model.config.use_cache = True\n"
                "if use_amp:\n"
                "    model = model.half()\n"
                "adapted = WhisperASRPipeline.from_model(model, processor, adapter='in-memory LoRA')\n"
                "adapted_transcripts = transcribe_all(adapted, eval_clips)\n"
                "adapted_wer = corpus_word_error_rate(eval_references, adapted_transcripts)\n"
                "del adapted\n"
                "report = adaptation_report(baseline_wer=round(baseline_wer, 4), adapted_wer=round(adapted_wer, 4), reloaded_wer=None, n_eval=len(eval_clips), history=history, dataset=DATASET, sample_kind=sample_kind)\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(report, handle, indent=2, ensure_ascii=False)\n"
                "adapted_edits = word_error_breakdown(eval_references, adapted_transcripts)\n"
                "report['edit_breakdown'] = {{'baseline': baseline_edits, 'adapted': adapted_edits, 'eval_transcripts_also_in_train': EVAL_TRANSCRIPTS_IN_TRAIN}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(report, handle, indent=2, ensure_ascii=False)\n"
                "print({{'baseline_wer': report['baselines'][0]['word_error_rate'], 'adapted_wer': adapted_wer, 'wer_delta': round(adapted_wer - baseline_wer, 4), 'verdict': report['verdict']}})\n"
                "print({{'edits_baseline': baseline_edits, 'edits_adapted': adapted_edits, 'eval_transcripts_also_in_train': EVAL_TRANSCRIPTS_IN_TRAIN}})\n"
                "changed = [(r, b, a) for r, b, a in zip(eval_references, baseline_transcripts, adapted_transcripts) if b != a]\n"
                "print({{'clips_with_changed_transcript': len(changed)}})\n"
                "for reference, before, after in changed[:3]:\n"
                "    print({{'reference': reference, 'baseline': before, 'adapted': after}})"
            ),
        },
        {
            "md": (
                "**What to notice (Section 9):** the adapted WER beside the baseline, both edit breakdowns, the duplicate count, and the "
                "changed clips.\n\n"
                "<details><summary>Check your reasoning</summary>In the earlier recorded run WER fell from 0.4387 to 0.4066 on 100 clips. "
                "That is about three points on one seeded split, a size another seed can reverse, and the changed clips showed the "
                "transcripts adopting the references' style. If substitutions fall while deletions and insertions barely move, the "
                "adapter mostly changed how words are written. If many held-out transcripts also occur in training, part of the gain may be "
                "memorised phrasing. Either way, it is evidence about this corpus's conventions, not that recognition improved in general.</details>\n\n"
                "## 10. Export the adapter bundle, then prove it reloads against the verified base · [Engineering]\n\n"
                "The deliverable is the **adapter bundle**, not a copy of the base model (ART1/ART4): `export_adapter_bundle` "
                "writes `adapter_model.safetensors` (a few tens of MB) and `adapter_config.json`, `metrics.json`, "
                "`provenance.json` (notebook source revision, base model identifier and immutable revision, dataset identity "
                "and split digest, hyperparameters, runtime) and an `artifact-manifest.json` listing every file with its size "
                "and SHA-256, and refuses an adapter whose saved `B` matrices are all zero. The bundle is zipped under `outputs/`.\n\n"
                "Then the notebook proves the bundle is usable from disk (VER1–VER5): the training model is released, "
                "`WhisperASRPipeline.from_pretrained(weights_dir=WEIGHTS_DIR, adapter_dir=...)` loads the **verified base "
                "snapshot** and merges the saved adapter, `verify_adapter_merge` checks on the probe module that "
                "`W_reloaded == W_base + (alpha / r) * B @ A` read back from the bundle (this proves the adapter was applied "
                "to the fresh weights however small its effect on the transcripts), and the held-out clips are transcribed "
                "again through the same pipeline — the run fails unless the reloaded transcripts agree with the in-memory "
                "adapted transcripts on at least 95% of the clips (float16 decoding is not bit-exact across two loads). The "
                "reloaded WER is added to the evaluation report, and the result, metrics and provenance are exported."
            ),
            "code": (
                "import math\n"
                "import shutil\n"
                "import zipfile\n"
                "from pathlib import Path\n\n"
                "ADAPTER_DIR = Path('outputs/whisper-asr-lora-adapter')\n"
                "ARTIFACT_ZIP = Path('outputs/whisper-asr-lora-adapter.zip')\n"
                "metrics = {{'baseline_wer': round(baseline_wer, 4), 'adapted_wer': round(adapted_wer, 4), 'wer_delta': round(adapted_wer - baseline_wer, 4), 'eval_clips': len(eval_clips), 'history': history}}\n"
                "PROVENANCE = {{\n"
                "    'artifactFormat': ADAPTER_BUNDLE_FORMAT,\n"
                "    'artifactFormatVersion': ADAPTER_BUNDLE_FORMAT_VERSION,\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'baseModel': MODEL_ID,\n"
                "    'baseModelRevision': MODEL_REVISION,\n"
                "    'baseModelLicense': MODEL_LICENSE,\n"
                "    'trustRemoteCode': False,\n"
                "    'dataset': {{**DATASET, 'language': LANGUAGE, 'train_clips': len(train_clips), 'eval_clips': len(eval_clips), 'seed': SEED, 'split_digest': SPLIT_DIGEST}},\n"
                "    'training': {{'method': 'lora', 'epochs': EPOCHS, 'batch_size': BATCH_SIZE, 'grad_accum': GRAD_ACCUM, 'learning_rate': LEARNING_RATE, 'lora_rank': LORA_RANK, 'lora_alpha': LORA_ALPHA, 'target_modules': LORA_TARGETS, 'mixed_precision': 'float16' if use_amp else None, 'seconds': TRAINING_SECONDS, 'peak_gpu_gib': PEAK_GPU_GIB, 'optimizer_steps': OPTIMIZER_STEPS}},\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'peft': peft.__version__, 'device': DEVICE}},\n"
                "}}\n"
                "manifest = export_adapter_bundle(model, ADAPTER_DIR, metrics=metrics, provenance=PROVENANCE)\n"
                "ARTIFACT_ZIP.unlink(missing_ok=True)\n"
                "with zipfile.ZipFile(ARTIFACT_ZIP, 'w', zipfile.ZIP_STORED) as archive:\n"
                "    for p in sorted(ADAPTER_DIR.rglob('*')):\n"
                "        if p.is_file():\n"
                "            archive.write(p, p.relative_to(ADAPTER_DIR).as_posix())\n"
                "zip_sha256 = hashlib.sha256(ARTIFACT_ZIP.read_bytes()).hexdigest()\n"
                "print({{'adapter_dir': str(ADAPTER_DIR), 'files': len(manifest), 'zip_mib': round(ARTIFACT_ZIP.stat().st_size / 1024 ** 2, 1), 'zip_sha256': zip_sha256}})\n\n"
                "del model, base_model, optimizer, scaler\n"
                "gc.collect()\n"
                "if use_amp:\n"
                "    torch.cuda.empty_cache()\n"
                "reloaded = WhisperASRPipeline.from_pretrained(device=DEVICE, weights_dir=WEIGHTS_DIR, allow_download=False, adapter_dir=ADAPTER_DIR)\n"
                "weight_tolerance = 1e-3 if reloaded.model.dtype == torch.float16 else 1e-5\n"
                "reload_weight_check = verify_adapter_merge(ADAPTER_DIR, PROBE_MODULE, probe_base_weight, reloaded.model.get_submodule(PROBE_MODULE).weight, rank=LORA_RANK, alpha=LORA_ALPHA, tolerance=weight_tolerance)\n"
                "reloaded_transcripts = transcribe_all(reloaded, eval_clips)\n"
                "reloaded_wer = corpus_word_error_rate(eval_references, reloaded_transcripts)\n"
                "agreement = sum(a == r for a, r in zip(adapted_transcripts, reloaded_transcripts))\n"
                "if agreement < math.ceil(0.95 * len(eval_clips)):\n"
                "    raise RuntimeError(f'Reloaded adapter reproduces only {{agreement}}/{{len(eval_clips)}} in-memory adapted transcripts')\n"
                "metrics['reloaded_wer'] = round(reloaded_wer, 4)\n"
                "metrics['reload_agreement'] = f'{{agreement}}/{{len(eval_clips)}}'\n"
                "metrics['clips_changed_vs_baseline'] = sum(b != r for b, r in zip(baseline_transcripts, reloaded_transcripts))\n"
                "metrics['reload_weight_check'] = reload_weight_check\n"
                "report = adaptation_report(baseline_wer=metrics['baseline_wer'], adapted_wer=metrics['adapted_wer'], reloaded_wer=metrics['reloaded_wer'], n_eval=len(eval_clips), history=history, dataset=DATASET, sample_kind=sample_kind)\n"
                "report['edit_breakdown'] = {{'baseline': baseline_edits, 'adapted': adapted_edits, 'reloaded': word_error_breakdown(eval_references, reloaded_transcripts), 'eval_transcripts_also_in_train': EVAL_TRANSCRIPTS_IN_TRAIN}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(report, handle, indent=2, ensure_ascii=False)\n"
                "print({{'reloaded_wer': metrics['reloaded_wer'], 'reload_agreement': metrics['reload_agreement'], 'clips_changed_vs_baseline': metrics['clips_changed_vs_baseline'], 'adapter': reloaded.adapter, 'adapter_sha256': reloaded.adapter_sha256, 'source': reloaded.source, 'reload_weight_check': reload_weight_check}})\n\n"
                "payload = {{\n"
                "    'metrics': metrics,\n"
                "    'evaluation_report': report,\n"
                "    'input_manifest': {{k: v for k, v in input_manifest.items() if k != 'inputs'}},\n"
                "    'examples': [{{'reference': r, 'baseline': b, 'reloaded': a}} for r, b, a in list(zip(eval_references, baseline_transcripts, reloaded_transcripts))[:5]],\n"
                "    'artifact': {{'zip': str(ARTIFACT_ZIP), 'sha256': zip_sha256, 'adapter_sha256': reloaded.adapter_sha256, 'files': manifest}},\n"
                "    'provenance': PROVENANCE,\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'peft': peft.__version__, 'device': reloaded.device}},\n"
                "    'sample': {{'kind': sample_kind, 'dataset': DATASET, 'language': LANGUAGE, 'split_digest': SPLIT_DIGEST}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(payload, handle, indent=2, ensure_ascii=False)\n"
                "shutil.copy(ADAPTER_DIR / 'metrics.json', 'outputs/{stem}_metrics.json')\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice (Section 10):** `reload_agreement` (at least 95 of 100), the reloaded WER equal or close to the adapted WER, a "
        "`reload_weight_check` that passed, and the exported files.\n\n"
        "## 11. Activity: change one thing — the number of epochs · [Concept]\n\n"
        "Optional; **Predict → Change one thing → Run → Observe → Explain**. It changes nothing unless you do it.\n\n"
        "1. **Predict:** with `EPOCHS = 1` instead of 2, will the adapted WER be higher or lower than with two epochs? What will the "
        "validation loss do?\n"
        "2. **Change:** in Section 8 set `EPOCHS = 1`. Change nothing else. Note the Section 8 and 9 numbers of your first run first: the "
        "next step overwrites `outputs/`.\n"
        "3. **Run:** select the **Section 4** cell and choose *Runtime → Run after*. Section 4 rebuilds the same seeded split, Section 6 "
        "rebuilds the baseline pipeline from the verified snapshot (no download) and records the baseline again, and Sections 7–10 train, "
        "evaluate, export and reload a fresh adapter.\n"
        "4. **Observe:** compare the loss history, the adapted WER, the edit breakdown and the number of changed clips with your first run.\n"
        "5. **Explain:** in one sentence, why can one epoch give a WER close to two epochs while the validation loss tells a different story, "
        "and why does a difference of a point or two on 100 clips not settle which setting is better?\n\n"
        "<details><summary>Check your reasoning</summary>With half the optimizer steps the adapter moves less, so expect a smaller change from "
        "the baseline; in the earlier run the epoch-1 validation loss (0.578) was lower than the epoch-2 one (0.612), so loss alone would "
        "favour one epoch while WER favoured two. Loss and WER measure different things (Section 8). With 100 clips and one seed, a point or "
        "two of WER is within what another seed can produce; to choose a setting you would need several seeds, and the choice must not be "
        "made on the same clips you report as the final result.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The adapted transcripts are model-generated. The baseline, adapted and reloaded WER figures are corpus-level numbers on one seeded "
        "held-out split of one locale of one public corpus (or of the uploaded BYOD set) and must not be generalized to other languages, "
        "speakers, domains, or capture conditions; a WER that moved by a few points on 100 short utterances is within the range where a "
        "different seed can change the sign, and no dispersion estimate is computed (EVAL5/ENV8). The corpus's references are informal "
        "transcriptions, so part of a gain can be the adapter learning their spelling conventions; the edit breakdown and the changed clips "
        "show how much, and the duplicate count shows how many held-out phrasings were also seen in training. The adapter specializes the "
        "model toward the training distribution and can degrade it elsewhere (catastrophic forgetting); the tutorial measures nothing outside "
        "the held-out split. Training and validation loss are optimisation evidence only. The pipeline provides no diarization, speaker "
        "identity, biometric inference, or calibrated transcript-confidence threshold, and the adapter inherits the license obligations of "
        "both the base weights (MIT) and the training data (CC-BY-4.0 for the default sample).\n\n"
        "Successful execution proves that the recorded repository revision's pipeline module, carried in this notebook, can acquire and "
        "digest-verify the pinned model, load and resample the demonstrated data, validate it, record a zero-shot baseline through the public "
        "pipeline, train LoRA adapters with the shown configuration in an isolated, hash-locked environment, export a manifested adapter "
        "bundle, and reload that bundle against the verified base with a weight-level merge check and transcript agreement — in the tested "
        "runtime, without the repository being reachable. It does **not** establish benchmark superiority, deployment calibration, safety for "
        "high-consequence use, or that the adapter generalises beyond the split it was measured on.\n\n"
        "**Try next** (each changes only form fields; re-run from the cell you changed with *Runtime → Run after*): change `LOCALE` to "
        "another whitespace-delimited language and compare the baseline/adapted delta; change `SEED` and see how much the delta moves; "
        "halve `LEARNING_RATE` and watch whether the validation loss and the WER move together; bring a few dozen clips of your own domain "
        "speech through BYOD and read the report's `needs` field before trusting the number.\n\n"
        "## Troubleshooting\n\n"
        "| Symptom | Likely cause | What to do |\n"
        "|---|---|---|\n"
        "| Section 1 stops with `This notebook needs a Linux x86_64 runtime` | a local Windows or macOS kernel, or an ARM machine | Use Google Colab or Kaggle; the lock holds manylinux x86_64 wheels. |\n"
        "| Section 1 fails while downloading, or `The pinned uv wheel failed its size/SHA-256 check` | a network failure, or an altered download | Run the Section 1 install cell again; a repeated mismatch means the download is being altered — never edit the digest. |\n"
        "| `holds Python …, not 3.12.12` in Section 1 | an older `dimer_isolated_env/` folder from another notebook version | Delete that folder (or start a fresh runtime) and run the install cell again. |\n"
        "| `The isolated environment's Python process exited` | the worker ran out of memory | Lower `BATCH_SIZE` (and raise `GRAD_ACCUM`) in Section 8, restart the session and choose *Runtime → Run all*. |\n"
        "| `CUDA out of memory` in Section 8 | the GPU is smaller than 16 GiB or another process holds memory | Lower `BATCH_SIZE`, raise `GRAD_ACCUM` to keep the effective batch, and run again from Section 7. |\n"
        "| Everything is very slow and Section 1 reports `cuda: False` | no GPU is attached | Choose *Runtime → Change runtime type → T4 GPU* and *Runtime → Run all*; on CPU lower `TRAIN_CLIPS`, `EVAL_CLIPS` and `EPOCHS` first. |\n"
        "| A Hub download fails in Section 3 or 4, or `sha256 … != manifest` | a transient Hugging Face failure, or a changed file | Run that cell again; a digest mismatch is never loaded — do not edit the manifest. |\n"
        "| `NameError: name 'pipe' is not defined` | a notebook from before this fix | Regenerate or reopen this version; Section 6 now rebuilds `pipe` itself on a re-run. |\n"
        "| `BYOD needs exactly one .csv …` or `… names N audio file(s) that were not supplied` in Section 4 | the CSV is missing, doubled, or names files you did not include | Supply one `.csv` with `file,text` columns and every audio file it names (same names, no folders inside the zip needed). |\n"
        "| `…: not an audio file soundfile can read` in Section 4 | a file is not audio, is corrupt, or uses an unsupported format | Convert it to WAV or FLAC and try again. |\n"
        "| `BYOD needs at least 10 usable clips …` | too few clips, or many over 30 s | Add clips, or cut long recordings into pieces of at most 30 s. |\n"
        "| `TRAIN_CLIPS + EVAL_CLIPS … must fit` | the locale has fewer clips than requested | Lower `TRAIN_CLIPS` or `EVAL_CLIPS` in Section 4. |\n"
        "| `Reloaded adapter reproduces only …` in Section 10 | the bundle did not reload as trained | Re-run from Section 7; do not ship the bundle if it repeats. |\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional. Fill in from your own run, one sentence each:\n\n"
        "1. The zero-shot WER was ___ (S ___ / I ___ / D ___); after adaptation it was ___ (S ___ / I ___ / D ___); reloaded ___.\n"
        "2. Training loss went ___ → ___ and validation loss ___ → ___, which means ___.\n"
        "3. ___ held-out transcripts also occurred in training, and the changed clips show the adapter mainly changed ___.\n"
        "4. What this result can show about LoRA adaptation on this corpus, and what it cannot: ___.\n"
        "5. What I would need before using such an adapter on my own recordings: ___.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/whisper-asr-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/whisper-asr-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/whisper-asr-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/openai/whisper\n"
        "- Whisper paper: https://arxiv.org/abs/2212.04356\n"
        "- LoRA paper: https://arxiv.org/abs/2106.09685\n"
        "- Public sample: https://huggingface.co/datasets/PolyAI/minds14"
    ),
}
